### ISSUE TITLE
THIS IS A DEAD PROJECT

### ISSUE THREAD

**Issue by DeadZen** [autumnai/leaf#122]
Save the time I wasted; Yes, the potential for AI in Rust is far beyond the potential for it in Python.
I understand that much, Unfortunately, the authors stopped and gave up on the infrastructure;
and without so much as mentioning it on the repository.

Alas I had to find out here.. after weeks of wondering wtf, why doesn't this work in any environment.
https://www.bountysource.com/teams/autumnai/issues?tracker_ids=24995999
 
Apparently important project updates, go on blogs now, and not the project README's.. 
https://medium.com/@mjhirn/tensorflow-wins-89b78b29aafb

Maybe someone update the repo and call it abandonware.

Maybe someone can figure out why no one can get past the errors:
: undefined reference to `cudnnSetConvolutionNdDescriptor_v3'
: undefined reference to `cudnnConvolutionBackwardFilter_v3'
: undefined reference to `cudnnConvolutionBackwardData_v3'
          
Maybe someone whose interested in the technology could fork it.
I dunno, I find it really frustrating.. (╯°□°）╯︵ ┻━┻

**Comment by hobofan** [comment]
There is already a longstanding issue for this (the most discussed one of the repo): https://github.com/autumnai/leaf/issues/108

**Comment by hobofan** [comment]
> Maybe someone can figure out why no one can get past the errors:
: undefined reference to cudnnSetConvolutionNdDescriptor_v3' : undefined reference tocudnnConvolutionBackwardFilter_v3'
: undefined reference to `cudnnConvolutionBackwardData_v3'

You most likely have a newer version of cuDNN installed than is targeted by Leaf
