### ISSUE TITLE
take layer metadata into layer struct

### ISSUE THREAD

**Issue by MichaelHirn** [autumnai/leaf#16]
At the moment the [`Network`][1] stores the layers and metadata about the layers in two different arrays with matching indices. This is Caffe legacy.

We would like to take the metadata about the layer into the layer struct as this cleanes up the structure and makes the scope of layers clearer.

[1]: http://autumnai.github.io/leaf/leaf/network/struct.Network.html

**Comment by hobofan** [comment]
Has been done in #49.
