### ISSUE TITLE
implement GPU support

### ISSUE THREAD

**Issue by MichaelHirn** [autumnai/leaf#22]
To provide state-of-the-art performance for training and running DNNs and comparing benchmarks for the first time with other Deep Learning Frameworks, we will need GPU support. 

A not exhaustive list of actions I am about to take in order to make this happen.

* Digesting more information about GPU programming
* Preparing [Phloem][phloem] for GPU/CPU support with [Arrayfire][arrayfire].
* abstracting mathematical operations from Leaf and putting it all back together.

[phloem]: github.com/autumnai/phloem
[arrayfire]: https://github.com/arrayfire/arrayfire-rust

**Comment by MichaelHirn** [comment]
Progress of the backend-agnostic, High Performance Computation part can be tracked at
https://github.com/autumnai/collenchyma

Should not take much longer until we have GPU supported, ready-to-run Machine Intelligence. Cuda will be first. OpenCL and native Host CPU is easy with Collenchyma, though.

**Comment by hobofan** [comment]
Has been done with #49.
