### ISSUE TITLE
Leaf on Rust stable

### ISSUE THREAD

**Issue by MichaelHirn** [autumnai/leaf#42]
As pointed out by @mitchmindtree on #40, Leaf doesn't build under stable, yet. I don't think that any important feature currently prevents us from supporting Rust stable (@hobofan might comment on this in more detail). Supporting Rust stable on Leaf, would increase its accessibility, dramatically.

**Comment by hobofan** [comment]
After merging #49 Leaf now builds on Rust stable and beta and passing Travis tests on all release channels are now required.
