### ISSUE TITLE
Create Leaf Book / high-level documentation

### ISSUE THREAD

**Issue by MichaelHirn** [autumnai/leaf#91]
I feel like, the entrance barrier for (Rust) Developers to engage with Leaf and Machine Learning, for contributions and hacking-away purposes, is still far too high. Partly because the concepts of Machine Learning (Deep Learning) are not yet widely known and partly because not many are familiar with the general design of a Machine Learning framework - compared e.g. to the general design of a Web framework.

The Leaf Book, should provide a practical introduction to Deep Learning for developers. Explain the easy Leaf API and provide examples for popular use-cases like adding a new Layer, Machine Learning across multiple devices and co. After reading it, a developer should feel comfortable hacking on Leaf, even if she has no prior knowledge about Deep Learning ( Deep Learning is really easy).

@hobofan pointed out in #45 interactive documentation for Layers. I am not sure to what extent they can be provided here with the Leaf Book. For the interactive layer documentation, I have something with Jupyter in mind, which would require a Rust kernel first, though. But other options for interactive layer documentation are welcome.

For the book I am trying [mdBook](https://github.com/azerupi/mdBook) as it gives a nice layout and allows it to place the book inside the leaf project. Feedback on the choice is welcome.

**Comment by ujh** [comment]
Sounds good! I can be one of your Guinea pigs for this. I'd be fine with requiring some prior knowledge on ML and deep learning provided that you link to good introductory material. I mean, there must be good material out there and I don't see the point of making the effort to duplicating this. At least not initially.

**Comment by MichaelHirn** [comment]
Ohh, I like that. Thank you for helping out. Progress can be tracked at  the [MichaelHirn/book](https://github.com/MichaelHirn/leaf/tree/book/doc) branch for now. I plan to make a WIP PR as soon as the first basics are there.

I also agree with your idea on requiring a basic understanding of ML/Deep Learning for the Leaf Book. I actually don't know a lot of good material for this. One that comes to my mind is [A 'brief' history of Deep Learning](http://www.andreykurenkov.com/writing/a-brief-history-of-neural-nets-and-deep-learning/) although a more basic introduction is still required.

BTW, the Book can be build after cloning the branch with

```bash
~/.cargo/bin/mdbook watch ./doc
```

**Comment by mgattozzi** [comment]
I would also be interested in helping out/being a guinea pig. I've been doing Machine Learning at school so contributing to a project like this would be beneficial in expanding my knowledge of it. Especially a Rust based one.

**Comment by ujh** [comment]
The following (free) online book has been recommended to me as an introduction to deep learning: http://neuralnetworksanddeeplearning.com/

I haven't read it yet so I can't say if it's good or not.

**Comment by mgattozzi** [comment]
@ujh Thanks for the link! I'll dig into it over the weekend.

**Comment by alexandermorozov** [comment]
There is also http://cs231n.github.io/. It's quite easy to follow and isn't very heavy on math, but reading it once from start to end feels enough to be able to implement a working NN.

**Comment by MichaelHirn** [comment]
I think, the first version of the book would be ready for review.

I hosted the first (not yet published) version at http://autumnai.com/leaf/book/

Looking forward to hear what you think :)

**Comment by KodrAus** [comment]
Thanks for the awesome work @MichaelHirn I've opened a PR for my copyediting as I go.
