### ISSUE TITLE
Unresolved Import ConvolutionConfig / Pooling

### ISSUE THREAD

**Issue by KodrAus** [autumnai/leaf#92]
I'm trying to fiddle with leaf-examples using the latest source; with the fix for history tensors.

The main error I'm getting right now is:

```
`ConvolutionConfig` does not name a structure
...
`PoolingConfig` does not name a structure
```

It looks like this is because the [module exports](https://github.com/autumnai/leaf/blob/master/src/layers/common/mod.rs#L13) for `leaf::layers::common::convolution` and `leaf::layers::common::pooling` are feature gated to only be compiled when using `cuda` without `native`.

I don't understand what this is about? You'd think you'd always need `native` if compiling with `cuda` to be able to sync the memory back and read results?

**Comment by hobofan** [comment]
There is some explanation for that here: https://github.com/autumnai/leaf/blob/3b25a48c2c2ceb49e4f9d462a8666d0adad38383/FEATURE-FLAGS.md

**Comment by KodrAus** [comment]
Ah thanks, that makes sense. I'll have to revisit the `Tensor` docs, I thought you needed the native backend to sync memory from the GPU to read

**Comment by hobofan** [comment]
Yeah, you do, that's why even when the `native` feature of Leaf is missing we still require the `native` feature of its Collenchyma dependency.

**Comment by KodrAus** [comment]
_Ahh_ yeh, Collenchyma's the one that manages the memory, isn't it. Thanks, I follow now
